id: P7A06A4AA
initial_creation_type: input
source_metadata:
  title: Fasting Ritual Series
  language: bo
  description: 'Texts related to the two-day ritual of fasting and silence known in
    Tibetan as Nyungné (smyung gnas):'
  volume:
    eadfd16011954dbd938319cd4653d5da:
      title: 'Excellent Intention: A Simple Fasting (Nyungne) Ritual'
      parent: Practices
created_at: '2022-03-01T03:40:48.590094'
last_modified_at: '2022-03-01T03:40:48.590097'
